# cloudbuild/cloudbuild.yaml

steps:
  - name: 'hashicorp/terraform:1.3.0'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Authenticate with GCP
        echo $GOOGLE_CREDENTIALS | base64 --decode > /tmp/credentials.json
        gcloud auth activate-service-account --key-file=/tmp/credentials.json
        gcloud config set project $PROJECT_ID

        # Initialize Terraform with backend config
        terraform init -backend-config="bucket=terraform-state-semantic-dev" -backend-config="prefix=terraform/client_state/${NEW_CLIENT_ID}"

        # Validate Terraform configuration
        terraform validate

        # Plan Terraform changes
        terraform plan -out=tfplan

        # Apply Terraform changes
        terraform apply -auto-approve tfplan

    env:
      - 'GOOGLE_CREDENTIALS=${_GOOGLE_CREDENTIALS}'
      - 'PROJECT_ID=${_PROJECT_ID}'
      - 'NEW_CLIENT_ID=${_NEW_CLIENT_ID}'
      - 'NEW_CLIENT_TOKEN=${_NEW_CLIENT_TOKEN}'
      - 'MASTER_SA_EMAIL=${_MASTER_SA_EMAIL}'