name: Deploy Infrastructure

on:
  repository_dispatch:
    types: [new_client]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Configure GCP Credentials
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: semantc-dev

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init

      - name: Validate Terraform
        working-directory: terraform
        run: terraform validate

      - name: Plan Terraform
        working-directory: terraform
        run: terraform plan -out=tfplan -var="new_client_id=${{ github.event.client_payload.client_id }}" -var="new_client_token=${{ github.event.client_payload.client_token }}"

      - name: Apply Terraform
        working-directory: terraform
        run: terraform apply -auto-approve tfplan
